routes/web.php
<?php

/*
 * ----------------------------------------------------------------------
 * Starting web middleware to handle web requests
 * -----------------------------------------------------------------------
 */

/**
 * Frontend Routes
 * Namespaces indicate folder structure
 */
/**
 * Switch between the included languages
 */
Route::group(['namespace' => 'Language'], function () {
    require (__DIR__ . '/Routes/Language/Language.php');
});

/**
 * Frontend Routes
 * Namespaces indicate folder structure
 */
Route::group(['namespace' => 'Frontend'], function () {
    /* all the frontend routes without using Auth Controller */
    require (__DIR__ . '/Routes/Frontend/Frontend.php');
    /* all the frontend routes which use Auth Controller like login, register etc */
    require (__DIR__ . '/Routes/Frontend/Access.php');
});

/**
 * Backend Routes
 * Namespaces indicate folder structure
 * Admin middleware groups web, auth, and routeNeedsPermission
 */
Route::group(['namespace' => 'Backend', 'prefix' => '', 'middleware' => 'auth'], function () {
    /**
     * These routes need view-backend permission
     * (good if you want to allow more than one group in the backend,
     * then limit the backend features by different roles or permissions)
     *
     * Note: Administrator has all permissions so you do not have to specify the administrator role everywhere.
     */
    /* dashboard routes */
    require (__DIR__ . '/Routes/Backend/Dashboard.php');
    /* for list all the routes for access management */
    require (__DIR__ . '/Routes/Backend/Access.php');
    /* list all the routes for system definition/data registration */
    require (__DIR__ . '/Routes/Backend/Sysdef.php');
    /* list all the routes for the file module */
    require (__DIR__ . '/Routes/Backend/File.php');
    /* for list all the routes for the actions for viewing log history */
    require (__DIR__ . '/Routes/Backend/LogViewer.php');
});
Route::group(['namespace' => 'Backend\File\Register\Storage', 'prefix' => 'storage'], function () {
    /* all routes which create,delete,edit,update the files on the disk */
    require (__DIR__ . '/Routes/Storage/File.php');
    require (__DIR__ . '/Routes/Storage/Document.php');
});
Route::group(['namespace' => 'Backend\File\Report', 'prefix' => 'report'], function () {
    /* list all the routes for the report module */
    require (__DIR__ . '/Routes/Backend/Report.php');
});
/* all routes which need a free access and do not need to go through any middleware */
require (__DIR__ . '/Routes/Open.php');

app/Models/Access/Officer.php
<?php

namespace App\Models\Access;

use Illuminate\Database\Eloquent\Model;

/**
 * Class Officer
 */
class Officer extends Model
{
    protected $table = 'officer';

    protected $primaryKey = 'officer_id';

	public $timestamps = true;

    protected $fillable = [
        'firstname',
        'othernames',
        'username',
        'password',
        'email',
        'department_id',
        'officeid',
        'gender',
        'checked',
        'level_id',
        'lastlogin',
        'pic',
        'phone',
        'home',
        'zipcode',
        'birth_date',
        'active',
        'remember_token',
        'officer_checked',
        'checked_date'
    ];

    protected $guarded = [];

        
}

app/Models/Access/OfficerPermission.php
<?php

namespace App\Models\Access;

use Illuminate\Database\Eloquent\Model;

/**
 * Class OfficerPermission
 */
class OfficerPermission extends Model {

    protected $table = 'officer_permission';
    protected $primaryKey = 'officer_permission_id';
    public $timestamps = true;
    protected $fillable = [
	'officer_id',
	'permission_id',
	'status'
    ];
    protected $guarded = [];

}

app/Models/Access/OfficerRole.php
<?php

namespace App\Models\Access;

use Illuminate\Database\Eloquent\Model;

/**
 * Class OfficerRole
 */
class OfficerRole extends Model
{
    protected $table = 'officer_role';

    protected $primaryKey = 'officer_role_id';

	public $timestamps = true;

    protected $fillable = [
        'officer_id',
        'role_id',
        'status'
    ];

    protected $guarded = [];

        
}

app/Models/Access/Permission.php
<?php

namespace App\Models\Access;

use Illuminate\Database\Eloquent\Model;
use App\Models\Access\Traits\Relationship\PermissionRelationship;

/**
 * Class Permission
 */
class Permission extends Model {

    use PermissionRelationship;
    
    protected $table = 'permission';
    protected $primaryKey = 'permission_id';
    public $timestamps = true;
    protected $fillable = [
	'name',
	'is_super',
	'parent_id',
	'description'
    ];
    protected $guarded = [];

}

app/Models/Access/PermissionDependency.php
<?php

namespace App\Models\Access;

use Illuminate\Database\Eloquent\Model;
use App\Models\Access\Traits\Relationship\PermissionDependencyRelationship;

/**
 * Class PermissionDependency
 */
class PermissionDependency extends Model {
    
    use PermissionDependencyRelationship;

    protected $table = 'permission_dependency';
    protected $primaryKey = 'permission_dependency_id';
    public $timestamps = true;
    protected $fillable = [
	'permission_id',
	'dependency_id'
    ];
    protected $guarded = [];
    
}

app/Models/Access/PermissionGroup.php
<?php

namespace App\Models\Access;

use Illuminate\Database\Eloquent\Model;
use App\Models\Access\Traits\Relationship\PermissionGroupRelationship;

/**
 * Class Permission
 */
class PermissionGroup extends Model {
    
    use PermissionGroupRelationship;

    protected $table = 'permission_group';
    protected $primaryKey = 'permission_group_id';
    public $timestamps = true;
    protected $fillable = [
    ];
    protected $guarded = [];
    
}

app/Models/Access/Role.php
<?php

namespace App\Models\Access;

use Illuminate\Database\Eloquent\Model;
use App\Models\Access\Traits\Relationship\RoleRelationship;
use App\Models\Access\Traits\Attribute\RoleAttribute;
use App\Models\Access\Traits\RoleAccess;

/**
 * Class Role
 */
class Role extends Model
{
    
    use RoleRelationship, RoleAttribute, RoleAccess;
    
    protected $table = 'role';

    protected $primaryKey = 'role_id';

	public $timestamps = true;

    protected $fillable = [
        'name',
        'sys_role'
    ];

    protected $guarded = [];

        
}

app/Models/Access/RolePermission.php
<?php

namespace App\Models\Access;

use Illuminate\Database\Eloquent\Model;

/**
 * Class RolePermission
 */
class RolePermission extends Model {

    protected $table = 'role_permission';
    protected $primaryKey = 'role_permission_id';
    public $timestamps = true;
    protected $fillable = [
	'role_id',
	'permission_id',
	'status'
    ];
    protected $guarded = [];

}

app/Models/Access/Traits/Attribute/UserAttribute.php
<?php

namespace App\Models\Access\Traits\Attribute;

use Carbon\Carbon;

/**
 * Class UserAttribute
 * @package App\Models\Access\Traits\Attribute
 */
trait UserAttribute {

    /**
     * @return string
     */
    public function getConfirmedLabelAttribute() {
	if ($this->isConfirmed())
	    return "<label class='label label-success'>" . trans('labels.general.yes') . "</label>";
	return "<label class='label label-danger'>" . trans('labels.general.no') . "</label>";
    }

    /**
     * @return string
     */
    public function getAvailableLabelAttribute() {
	if ($this->isAvailable())
	    return "<label class='label label-success'>" . trans('labels.general.yes') . "</label>";
	return "<label class='label label-danger'>" . trans('labels.general.no') . "</label>";
    }

    public function getActiveLabelAttribute() {
	if ($this->isActive())
	    return "<label class='label label-success'>" . trans('labels.general.yes') . "</label>";
	return "<label class='label label-danger'>" . trans('labels.general.no') . "</label>";
    }

    /**
     * @return mixed
     */
    public function getPicAttribute($value) {
	if (is_null($value)) {
	    return asset_url() . '/images/anonymous.jpg';
	} else {
	    return public_url() . "/storage/profile/" . $value;
	}
    }

    public function getGenderLabelAttribute() {
	if ($this->gender == 'M') {
	    return "<label class='label label-success'>" . trans('labels.general.male') . "</label>";
	} else {
	    return "<label class='label label-success'>" . trans('labels.general.female') . "</label>";
	}
    }

    public function getLastloginAttribute($value) {
	if (!is_null($value)) {
	    return Carbon::parse($value)->diffForHumans();
	} else {
	    return "";
	}
    }

    public function getAdminAttribute() {
	$admins = $this->department->users()->whereHas('roles', function($query) {
		    $query->where('role.role_id', '=', 2);
		})->get();
	$officers = [];
	if (count($admins)) {
	    foreach ($admins as $admin) {
		$officers[] = $admin->name();
	    }
	    return implode("<br/>", $officers);
	}
	return "";
    }

    public function getRoleLabelAttribute() {
	$roles = [];
	if ($this->roles()->count() > 0) {
	    foreach ($this->roles as $role) {
		array_push($roles, $role->name);
	    }
	    return implode("<br/>", $roles);
	} else {
	    return trans('labels.general.none');
	}
    }

    /**
     * @return bool
     */
    public function isActive() {
	return $this->active == 1;
    }

    public function name() {
	return $this->firstname . ' ' . $this->othernames;
    }

    public function getFullNameAttribute() {
	return $this->firstname . ' ' . $this->othernames;
    }

    /**
     * @return bool
     */
    public function isConfirmed() {
	return $this->checked == 1;
    }

    /**
     * @return bool
     */
    public function isAvailable() {
	return $this->available == 1;
    }

    /**
     * @return string
     */
    public function getEditButtonAttribute() {
	if (access()->allow('edit_user')) {
	    //if ($this->officer_id != access()->id() And ! $this->hasRole('super')) {
	    return '<a href="' . route('access.user.edit', $this) . '"><i class="fa fa-pencil"></i>&nbsp;&nbsp;' . trans('buttons.general.crud.edit') . '</a> ';
	    //}
	}
    }

    /**
     * @return string
     */
    public function getDeleteButtonAttribute() {
	if (access()->allow('delete_user')) {
	    if ($this->officer_id != access()->id() And ( !$this->isAvailable() And ! $this->isConfirmed())) {
		return '<a href="' . route('access.user.destroy', $this) . '"
                 data-method="delete"
                 data-trans-button-cancel="' . trans('buttons.general.cancel') . '"
                 data-trans-button-confirm="' . trans('buttons.general.confirm') . '"
                 data-trans-title="' . trans('labels.general.warning') . '"
		 data-trans-text="' . trans('strings.backend.general.delete_message') . '"
                 ><i class="fa fa-trash"></i>&nbsp;&nbsp;' . trans('buttons.general.crud.delete') . '</a> ';
	    }
	}
	return '';
    }

    /**
     * @return string
     */
    public function getOutButtonAttribute() {
	if ($this->isActive() And $this->isConfirmed()) {
	    if (access()->allow('in_out_office')) {
		switch ($this->available) {
		    case 1:
			return '<a href="' . route('access.user.out', [
				    $this,
				    0
				]) . '"><i class="fa fa-sign-out"></i>&nbsp;&nbsp;' . trans('buttons.backend.access.users.out_office') . '</a> ';
		    // No break

		    case 0:
			return '<a href="' . route('access.user.out', [
				    $this,
				    1
				]) . '"><i class="fa fa-sign-in" data-toggle="tooltip"></i>&nbsp;&nbsp;' . trans('buttons.backend.access.users.in_office') . '</a> ';
		    // No break

		    default:
			return '';
		    // No break
		}
	    }
	}
	return '';
    }

    /**
     * @return string
     */
    public function getChangePasswordButtonAttribute() {
	if (access()->allow('change_user_password')) {
	    if (!$this->hasRole('super') And ! $this->hasRole('admin')) {
		return '<a href="' . route('access.user.change_password', $this) . '"><i class="fa fa-refresh"></i>&nbsp;&nbsp;' . trans('buttons.backend.access.users.change_password') . '</a> ';
	    }
	}
	return '';
    }

    /**
     * @return string
     */
    public function getConfirmButtonAttribute() {
	if (access()->allow('approve_user')) {

	    if (!$this->isAvailable() And ! $this->isConfirmed()) {
		return '<a href="' . route('access.user.approve', $this) . '"><i class="fa fa-check"></i>&nbsp;&nbsp;' . trans('buttons.general.approve') . '</a> ';
	    }
	}
    }

    /**
     * @return string
     */
    public function getStatusButtonAttribute() {
	if (($this->officer_id != access()->id()) Or ( $this->hasRole('super') And access()->hasRole('super') And $this->officer_id != access()->id())) {
	    if (access()->allow('deactivate_reactivate_user')) {
		switch ($this->active) {
		    case 0:
			return '<a href="' . route('access.user.activate', [
				    $this,
				    1
				]) . '"><i class="fa fa-play"></i>&nbsp;&nbsp;' . trans('buttons.backend.access.users.activate') . '</a> ';
		    // No break

		    case 1:
			return '<a href="' . route('access.user.activate', [
				    $this,
				    0
				]) . '"><i class="fa fa-pause"></i>&nbsp;&nbsp;' . trans('buttons.backend.access.users.deactivate') . '</a> ';
		    // No break

		    default:
			return '';
		    // No break
		}
	    }
	}
	return '';
    }

    /**
     * @return string
     */
    public function getActionButtonsAttribute() {
	return
		'<div class="btn-group">' .
		'<button type="button" class="btn btn-info btn-xs dropdown-toggle" data-toggle="dropdown" aria-expanded="false">' .
		trans('labels.general.actions') .
		'&nbsp;<span class="caret"></span>' .
		'</button>' .
		'<ul class="dropdown-menu dropdown-menu-right" role="menu">' .
		'<li>' . $this->getEditButtonAttribute() . '</li>' .
		'<li>' . $this->getOutButtonAttribute() . '</li>' .
		'<li>' . $this->getChangePasswordButtonAttribute() . '</li>' .
		'<li>' . $this->getStatusButtonAttribute() . '</li>' .
		'<li>' . $this->getConfirmButtonAttribute() . '</li>' .
		'<li>' . $this->getDeleteButtonAttribute() . '</li>' .
		'</ul>' .
		'</div>';
    }

}

app/Models/Access/Traits/Relationship/PermissionGroupRelationship.php
<?php

namespace App\Models\Access\Traits\Relationship;

/**
 * Class PermissionRelationship
 * @package App\Models\Access\Permission\Traits\Relationship
 */
trait PermissionGroupRelationship {

    /**
     * return @mixed
     */
    public function permissions(){
	return $this->hasMany(\App\Models\Access\Permission::class, 'permission_group_id', 'permission_group_id')->orderBy('permission_group_id', 'asc');
    }
    
}

app/Http/Controllers/Backend/Access/Role/RoleController.php
<?php

namespace App\Http\Controllers\Backend\Access\Role;

use App\Http\Controllers\Controller;
use Yajra\Datatables\Facades\Datatables;
use App\Repositories\Backend\Access\Role\EloquentRoleRepository;
use App\Http\Requests\Backend\Access\Role\UpdateRoleRequest;
use App\Repositories\Backend\Access\Permission\EloquentPermissionRepository;
use App\Repositories\Backend\Access\Permission\Group\EloquentPermissionGroupRepository;

/**
 * Class RoleController
 * @package App\Http\Controllers\Access
 */
class RoleController extends Controller {

    /**
     * @var RoleRepositoryContract
     */
    protected $roles;

    /**
     * @var PermissionRepositoryContract
     */
    protected $permissions;

    /**
     * @param RoleRepositoryContract       $roles
     * @param PermissionRepositoryContract $permissions
     */
    public function __construct(
    EloquentRoleRepository $roles, EloquentPermissionRepository $permissions
    ) {
	$this->roles = $roles;
	$this->permissions = $permissions;
    }

    /**
     * @return mixed
     */
    public function index() {
	return view('backend.access.roles.index');
    }

    /**
     * @param ManageRoleRequest $request
     * @return mixed
     */
    public function get() {
	return Datatables::of($this->roles->getForDataTable())
			->addColumn('permissions', function($role) {
			    $permissions = [];
			    if (count($role->permissions) > 0) {
				foreach ($role->permissions as $permission) {
				    array_push($permissions, $permission->display_name);
				}

				return implode(", ", $permissions);
			    } else {
				return '<span class="label label-danger">' . trans('labels.general.none') . '</span>';
			    }
			})
			->addColumn('users', function($role) {
			    return $role->users()->count();
			})
			->addColumn('actions', function($role) {
			    return $role->action_buttons;
			})
			->make(true);
    }

    /**
     * @param  PermissionGroupRepositoryContract $group
     * @return mixed
     */
    public function create(EloquentPermissionGroupRepository $group) {
	return view('backend.access.roles.create')
			->withGroups($group->getAllGroups());
    }

    /**
     * @return mixed
     */
    public function store(UpdateRoleRequest $request) {
	$this->roles->create($request->all());
	return redirect()->route('access.role.index')->withFlashSuccess(trans('alerts.backend.roles.created'));
    }

    /**
     * @param  $id
     * @param  PermissionGroupRepositoryContract $group
     * @return mixed
     */
    public function edit($id, EloquentPermissionGroupRepository $group) {
	$role = $this->roles->findOrThrowException($id, true);
	return view('backend.access.roles.edit')
			->withRole($role)
			->withRolePermissions($role->permissions->pluck('permission_id'))
			->withGroups($group->getAllGroups());
    }

    /**
     * @param  $id
     * @param  UpdateRoleRequest $request
     * @return mixed
     */
    public function update($id, UpdateRoleRequest $request) {
	$this->roles->update($id, $request->all());
	return redirect()->route('access.role.index')->withFlashSuccess(trans('alerts.backend.roles.updated'));
    }

    /**
     * @param  $id
     * @return mixed
     */
    public function destroy($id) {
	$this->roles->destroy($id);
	return redirect()->route('access.role.index')->withFlashSuccess(trans('alerts.backend.roles.deleted'));
    }

}

resources/views/backend/access/change_password.blade.php
@extends('backend.layouts.master', ['title' => trans('labels.backend.access.users.management'), 'header_title' => trans('labels.backend.access.users.management'), 'header_sub_title' => trans('labels.backend.access.users.change_password')])

@section('content')
@include('backend.access.includes.partials.header_buttons')
<br/>
<p>
    <b>{{ trans('labels.backend.access.users.change_password_for', ['user' => $user->firstname . ' ' . $user->othernames]) }}</b>
</p>
<hr/>
{!! Form::open(['route' => ['access.user.change_password', $user->officer_id], 'role' => 'form', 'method' => 'post']) !!}
<div class="row">
    <div class="col-md-12">
    <div class="form-group">
	{!! Form::label('password', trans('validation.attributes.backend.access.users.password'), ['class' => 'control-label symbol required']) !!}
	<span class="input-icon">
	    {!! Form::input('password', 'password', null, ['class' => 'form-control']) !!}
	    <i class="fa fa-lock"></i>
	</span>
	{!! $errors->first('password', '<span class="help-block label label-danger">:message</span>') !!}
    </div>
    <div class="form-group">
	{!! Form::label('password_confirmation', trans('validation.attributes.backend.access.users.password_confirmation'), ['class' => 'control-label symbol required']) !!}
	<span class="input-icon">
	    {!! Form::input('password', 'password_confirmation', null, ['class' => 'form-control']) !!}
	    <i class="fa fa-lock"></i>
	</span>
	{!! $errors->first('password_confirmation', '<span class="help-block label label-danger">:message</span>') !!}
    </div>
    </div>
</div>

<br/>
<div class="pull-left">
    <a href="{{route('access.user.index')}}" class="btn btn-danger btn-sm">{{ trans('buttons.general.cancel') }}</a>
</div>

<div class="pull-right">
    <input type="submit" class="btn btn-success btn-sm" value="{{ trans('buttons.general.crud.update') }}" />
</div>
<div class="clearfix"></div>

{!! Form::close() !!}
@stop

resources/views/backend/access/deactivated.blade.php
@extends('backend.layouts.master', ['title' => trans('labels.backend.access.users.management'), 'header_title' => trans('labels.backend.access.users.management'), 'header_sub_title' => trans('labels.backend.access.users.deactivated')])

@section('after-styles-end')
{{ Html::style(asset_url() . "/css/datatables/dataTables.bootstrap.min.css") }}
{{ Html::style(asset_url() . "/plugins/sweetalert/lib/sweet-alert.css") }}
@stop

@section('content')
@include('backend.access.includes.partials.header_buttons')
<br/>
<div class="table-responsive">
    <table id="users-table" class="table table-condensed table-hover">
	<thead>
	    <tr>
		<th>{{ trans('labels.backend.access.users.table.firstname') }}</th>
		<th>{{ trans('labels.backend.access.users.table.othernames') }}</th>
		<th>{{ trans('labels.backend.access.users.table.username') }}</th>
		<th>{{ trans('labels.backend.access.users.table.department') }}</th>
		<th>{{ trans('labels.backend.access.users.table.branch_name') }}</th>
		<th>{{ trans('labels.backend.access.users.table.region') }}</th>
		<th>{{ trans('labels.backend.access.users.table.confirmed') }}</th>
		<th>{{ trans('labels.backend.access.users.table.available') }}</th>
		<th>{{ trans('labels.backend.access.users.table.roles') }}</th>
		<th>{{ trans('labels.general.table.created') }}</th>
		<th>{{ trans('labels.general.table.last_updated') }}</th>
		<th>{{ trans('labels.general.actions') }}</th>
	    </tr>
	</thead>
    </table>
</div><!--table-responsive-->
@stop

@section('after-scripts-end')
{{ Html::script(asset_url() . "/js/backend/backend.js") }}
{{ Html::script(asset_url(). "/js/plugins/datatables/jquery.dataTables.min.js") }}
{{ Html::script(asset_url() . "/js/plugins/datatables/dataTables.bootstrap.min.js") }}
{{ Html::script(asset_url() . "/plugins/sweetalert/lib/sweet-alert.min.js") }}

<script>
    $(function () {
	$('#users-table').DataTable({
	    processing: true,
	    serverSide: true,
	    ajax: {
		url: '{{ route("access.user.get") }}',
		type: 'get',
		data: {column: 'active', value: 0}
	    },
	    columns: [
		{data: 'firstname', name: 'firstname'},
		{data: 'othernames', name: 'othernames'},
		{data: 'username', name: 'username'},
		{data: 'department', name: 'department'},
		{data: 'branch_name', name: 'branch_name'},
		{data: 'region', name: 'region'},
		{data: 'checked', name: 'checked'},
		{data: 'available', name: 'available'},
		{data: 'roles', name: 'roles'},
		{data: 'created_at', name: 'created_at'},
		{data: 'updated_at', name: 'updated_at'},
		{data: 'actions', name: 'actions'}
	    ],
	    order: [[0, "asc"]],
	    searchDelay: 500
	});
    });
</script>
@stop

resources/views/backend/access/index.blade.php
@extends('backend.layouts.master', ['title' => trans('labels.backend.access.users.management'), 'header_title' => trans('labels.backend.access.users.management'), 'header_sub_title' => trans('labels.backend.access.users.active')])

@section('after-styles-end')
{{ Html::style(asset_url() . "/css/datatables/dataTables.bootstrap.min.css") }}
{{ Html::style(asset_url() . "/plugins/sweetalert/lib/sweet-alert.css") }}
{{ Html::style(asset_url() . "/plugins/sweetalert/lib/google.css") }}
@stop

@section('content')
@include('backend.access.includes.partials.header_buttons')

@if (count($new_users))
@include('backend.access.includes.partials.group_buttons')
<br/>
@endif

<div class="table-responsive">
    <table id="users-table" class="table table-condensed table-hover">
        <thead>
            <tr>
                <th></th>
                <th>{{ trans('labels.backend.access.users.table.firstname') }}</th>
                <th>{{ trans('labels.backend.access.users.table.othernames') }}</th>
                <th>{{ trans('labels.backend.access.users.table.username') }}</th>
                <th>{{ trans('labels.backend.access.users.table.department') }}</th>
                <th>{{ trans('labels.backend.access.users.table.branch_name') }}</th>
                <th>{{ trans('labels.backend.access.users.table.region') }}</th>
                <th>{{ trans('labels.backend.access.users.table.confirmed') }}</th>
                <th>{{ trans('labels.backend.access.users.table.available') }}</th>
                <th>{{ trans('labels.backend.access.users.table.roles') }}</th>
                <th>{{ trans('labels.general.table.created') }}</th>
                <th>{{ trans('labels.general.table.last_updated') }}</th>
                <th>{{ trans('labels.general.actions') }}</th>
            </tr>
        </thead>
    </table>
</div><!--table-responsive-->
<hr/>

@stop

<!-- start: PAGE HISTORY CONTENT -->
@section('history')
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-info">
            <div class="panel-heading">
                <h4 class="panel-title"><span class="text-bold">{{ trans('history.backend.recent_history') }}</span></h4>                                    
            </div>
            <div class="panel-body">
                <!--Main content goes here-->
                <div class="table-responsive">
                    <table id="history-table" class="table table-condensed table-hover">
                        <thead>
                            <tr>
                                <th>{{ trans('labels.backend.access.users.table.history') }}</th>
                                <th>{{ trans('labels.general.table.created') }}</th>
                            </tr>
                        </thead>
                    </table>
                </div><!--table-responsive-->
            </div>
        </div>
    </div>
</div>
@stop
@section('history-scripts')
<script>
    $(function () {
        $('#history-table').DataTable({
            processing: true,
            serverSide: true,
            ajax: {
                url: '{{ route("backend.history", "access_management") }}',
                type: 'get',
                data: {column: 'active', value: 1}
            },
            columns: [
                {data: 'history', name: 'history'},
                {data: 'created_at', name: 'created_at'}
            ],
            order: [[0, "asc"]],
            searchDelay: 500
        });
    });
</script>
@stop
<!-- end: PAGE HISTORY CONTENT -->

@section('after-scripts-end')
{{ Html::script(asset_url() . "/js/backend/backend.js") }}
{{ Html::script(asset_url(). "/js/plugins/datatables/jquery.dataTables.min.js") }}
{{ Html::script(asset_url() . "/js/plugins/datatables/dataTables.bootstrap.min.js") }}
{{ Html::script(asset_url() . "/plugins/sweetalert/lib/sweet-alert.min.js") }}

<script>
    $(function () {
        $('#users-table').DataTable({
            processing: true,
            serverSide: true,
            stateSave: true,
            stateSaveCallback: function (settings, data) {
                localStorage.setItem('DataTables_' + settings.sInstance, JSON.stringify(data));
            },
            stateLoadCallback: function (settings) {
                return JSON.parse(localStorage.getItem('DataTables_' + settings.sInstance));
            },
            ajax: {
                url: '{{ route("access.user.get") }}',
                type: 'get',
                data: {column: 'active', value: 1}
            },
            columns: [
                {data: 'check', name: 'check', "orderable": false, "searchable": false},
                {data: 'firstname', name: 'firstname'},
                {data: 'othernames', name: 'othernames'},
                {data: 'username', name: 'username'},
                {data: 'department', name: 'department'},
                {data: 'branch_name', name: 'branch_name'},
                {data: 'region', name: 'region'},
                {data: 'checked', name: 'checked'},
                {data: 'available', name: 'available'},
                {data: 'roles', name: 'roles'},
                {data: 'created_at', name: 'created_at'},
                {data: 'updated_at', name: 'updated_at'},
                {data: 'actions', name: 'actions'}
            ],
            // order: [[3, "asc"]],
            searchDelay: 500
        });
    });
</script>


@stop